# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GzIS_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_cboxes = QtWidgets.QHBoxLayout()
        self.lay_cboxes.setObjectName("lay_cboxes")
        self.cbx_ar_pos = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_ar_pos.sizePolicy().hasHeightForWidth())
        self.cbx_ar_pos.setSizePolicy(sizePolicy)
        self.cbx_ar_pos.setMinimumSize(QtCore.QSize(0, 0))
        self.cbx_ar_pos.setStyleSheet("")
        self.cbx_ar_pos.setObjectName("cbx_ar_pos")
        self.lay_cboxes.addWidget(self.cbx_ar_pos)
        self.cbx_jsons = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_jsons.setObjectName("cbx_jsons")
        self.lay_cboxes.addWidget(self.cbx_jsons)
        self.gridLayout.addLayout(self.lay_cboxes, 0, 1, 1, 1)
        self.lay_contents = QtWidgets.QVBoxLayout()
        self.lay_contents.setObjectName("lay_contents")
        self.table_content = QtWidgets.QTableWidget(self.centralwidget)
        self.table_content.setObjectName("table_contents")
        self.table_content.setColumnCount(0)
        self.table_content.setRowCount(0)
        self.lay_contents.addWidget(self.table_content)
        self.gridLayout.addLayout(self.lay_contents, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.tilebar_custom = QtWidgets.QMenuBar(MainWindow)
        self.tilebar_custom.setGeometry(QtCore.QRect(0, 0, 759, 21))
        self.tilebar_custom.setObjectName("tilebar_custom")
        self.menuFilter = QtWidgets.QMenu(self.tilebar_custom)
        self.menuFilter.setObjectName("menuFilter")
        self.menuTest_Suites_isAccept = QtWidgets.QMenu(self.menuFilter)
        self.menuTest_Suites_isAccept.setObjectName("menuTest_Suites_isAccept")
        MainWindow.setMenuBar(self.tilebar_custom)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAll = QtWidgets.QAction(MainWindow)
        self.actionAll.setObjectName("actionAll")
        self.actionTrue = QtWidgets.QAction(MainWindow)
        self.actionTrue.setObjectName("actionTrue")
        self.actionFalse = QtWidgets.QAction(MainWindow)
        self.actionFalse.setObjectName("actionFalse")
        self.menuTest_Suites_isAccept.addAction(self.actionAll)
        self.menuTest_Suites_isAccept.addAction(self.actionTrue)
        self.menuTest_Suites_isAccept.addAction(self.actionFalse)
        self.menuFilter.addAction(self.menuTest_Suites_isAccept.menuAction())
        self.tilebar_custom.addAction(self.menuFilter.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter"))
        self.menuTest_Suites_isAccept.setTitle(_translate("MainWindow", "Test Suites isAccept"))
        self.actionAll.setText(_translate("MainWindow", "All"))
        self.actionTrue.setText(_translate("MainWindow", "True"))
        self.actionFalse.setText(_translate("MainWindow", "False"))
