# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/GzIs_error_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget()
        self.menubar = QtWidgets.QMenuBar()
        self.statusbar = QtWidgets.QStatusBar()
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.setup_ui()

    def setup_ui(self):
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 0, 1, 1, 1)

        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(size_policy)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        with open("UIs/GzIs_cbx_style_sheet.css", "r") as cbxsheet:
            self.comboBox.setStyleSheet(str(cbxsheet.read()))
        with open("UIs/GzIs_cbx_style_sheet.css", "r") as cbxsheet:
            self.comboBox_2.setStyleSheet(str(cbxsheet.read()))

        self.tabWidget.setMinimumSize(QtCore.QSize(720, 360))
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.setCentralWidget(self.centralwidget)
        with open("UIs/GzIS_tabwid_styel_sheet.css", "r") as twsheet:
            self.tabWidget.setStyleSheet(str(twsheet.read()))

        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 24))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)

        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslate_ui()
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
